[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[cursor]
blink_interval = 500

[cursor.style]
blinking = "Always"

[font]
size = 11.0

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

# This changes the output of <Ctrl-Shift> to allows its use in other programs like nvim in tmux
[keyboard]
  bindings = [
    { key = "f", mods = "Control | Shift", chars = "\u2660" }
  ]
