#!/usr/bin/bash
find_param="-mindepth 1 -maxdepth 1 -type d"
dir_list_rec=(
	~/
	~/work/ 
	~/ownCloud/ 
	~/ownCloud/dotfiles 
	~/ownCloud/config 
	~/ownCloud/programming/projects/ 
	~/ownCloud/programming/courses/ 
)
singles=(
	/home/cyphics/Documents/admin/CV/moi/
	)

if [[ $# -eq 1 ]]; then
    selected=$1
else
	list_one=$(find ${dir_list_rec[@]} $find_param)
	dir_list=("${list_one[@]}" "${singles[@]}")
	selected=$(echo "${list_one[@]}" | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

if [[ -z $TMUX ]] && [[ -n $(pgrep tmux) ]]; then
	echo "tmux is running but detached."
	tmux a
	exit
fi

session_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep -x tmux)

# If it's the first session
if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $session_name -c $selected
	echo "create session"
    exit 0
fi

# If the session don't exist already, create it
if ! tmux has-session -t="$session_name" 2> /dev/null; then
    tmux new-session -ds $session_name -c $selected
fi
# Then switch to it
tmux switch-client -t $session_name
